#INCLUDE <P16F877A.INC>

CONTA EQU 0X20

	ORG 0
	GOTO INICIO

	ORG 5

INICIO:
	CLRF CONTA		;(CONTA) <-- 0X00
CONTINUA1:
	INCF CONTA,F	;(CONTA) <-- (CONTA)+1
	MOVF CONTA,W	;W <-- CONTA
	SUBLW 0X09		;W <-- (CONTA)-W
	BTFSS STATUS,Z	;CONTA==0X09 STATUS.Z==1
	GOTO CONTINUA1	;NO, SIGUE INCREMENTANDO
	MOVLW 0X10		;SI, AHORA EL REGISTRO CONTIENE EL VALOR 0X10
	MOVWF CONTA		;(CONTA) <-- W
CONTINUA2:
	INCF CONTA,F	;(CONTA) <-- (CONTA)+1
	MOVF CONTA,W	;W <-- CONTA
	SUBLW 0X19		;W <-- (CONTA)-W
	BTFSS STATUS,Z	;CONTA==0X19  STATUS.Z==1
	GOTO CONTINUA2	;NO, SIGUE INCREMENTANDO CON LA SEGUNDA SUBRUTINA
	MOVLW 0X20		;SI, AHORA EL REGISTRO CONTIENE EL VALOR 0X20
	MOVWF CONTA		;(CONTA) <-- W
	GOTO INICIO

	END